stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"
  AWS_REGION: "eu-west-1"
  ECR_REGISTRY: "038547062468.dkr.ecr.$AWS_REGION.amazonaws.com"
  # Override in GitLab CI/CD variables if needed
  ECR_REPOSITORY: "ergoglobal-ai"
  ECS_CLUSTER: "ergoglobal-ai"
  ECS_SERVICE: "ergoglobal-ai"

build_and_push:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: ["--mtu=1460"]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - set -euo pipefail
    - apk add --no-cache aws-cli jq bash curl
    - aws --version
    - export AWS_DEFAULT_REGION="$AWS_REGION"
    - |
      if [ -z "${AWS_ROLE_ARN:-}" ]; then
        echo "ERROR: AWS_ROLE_ARN is not set" >&2
        exit 1
      fi
    - printf "%s" "${GITLAB_OIDC_TOKEN}" > /tmp/gitlab-oidc-token
    - export AWS_ROLE_ARN="$AWS_ROLE_ARN"
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/gitlab-oidc-token
    - aws sts get-caller-identity
    - aws ecr describe-repositories --repository-names "$ECR_REPOSITORY" || aws ecr create-repository --repository-name "$ECR_REPOSITORY"
    - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
  script:
    - docker build -f apps/ai-service/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" .
    - docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        docker tag "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" "$ECR_REGISTRY/$ECR_REPOSITORY:latest"
        docker push "$ECR_REGISTRY/$ECR_REPOSITORY:latest"
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

deploy_ecs:
  stage: deploy
  image:
    name: amazon/aws-cli:2.17.21
    entrypoint: [""]
  needs: ["build_and_push"]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - yum install -y jq gettext >/dev/null 2>&1 || true
    - aws --version
    - export AWS_DEFAULT_REGION="$AWS_REGION"
    - |
      if [ -z "${AWS_ROLE_ARN:-}" ]; then
        echo "ERROR: AWS_ROLE_ARN is not set" >&2
        exit 1
      fi
    - printf "%s" "${GITLAB_OIDC_TOKEN}" > /tmp/gitlab-oidc-token
    - export AWS_ROLE_ARN="$AWS_ROLE_ARN"
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/gitlab-oidc-token
    - aws sts get-caller-identity
    - cd "$CI_PROJECT_DIR"
  script:
    - mkdir -p deploy/ecs
    - IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    - jq --arg img "$IMAGE_URI" --arg region "$AWS_REGION" \
      '.containerDefinitions[0].image=$img | .containerDefinitions[0].logConfiguration.options["awslogs-region"]=$region' \
      deploy/ecs/taskdef.template.json > deploy/ecs/taskdef.rendered.json
    - |
      LOG_GROUP=$(jq -r '.containerDefinitions[0].logConfiguration.options["awslogs-group"]' deploy/ecs/taskdef.rendered.json)
      if ! aws logs describe-log-groups --log-group-name-prefix "$LOG_GROUP" | jq -e \
        ".logGroups[] | select(.logGroupName == \"$LOG_GROUP\")" >/dev/null 2>&1; then
        aws logs create-log-group --log-group-name "$LOG_GROUP"
      fi
    - |
      TASK_DEF_ARN=$(aws ecs register-task-definition \
        --cli-input-json file://deploy/ecs/taskdef.rendered.json \
        | jq -r '.taskDefinition.taskDefinitionArn')
      echo "Registered task definition: $TASK_DEF_ARN"
    - aws ecs update-service --cluster "$ECS_CLUSTER" --service "$ECS_SERVICE" --task-definition "$TASK_DEF_ARN"
    - aws ecs wait services-stable --cluster "$ECS_CLUSTER" --services "$ECS_SERVICE"
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
