openapi: 3.0.3
info:
  title: Monorepo Template API
  description: An Express.js API template with TypeScript, designed for modularity, security, and extensibility in a monorepo environment.
  version: 1.0.0
servers:
  - url: http://localhost:4000
    description: Local development server
tags:
  - name: Auth
    description: Authentication endpoints
  - name: User
    description: Authentication endpoints
  - name: Health
    description: Health endpoints
